# Generated by Django 3.2 on 2022-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_type',
            field=models.CharField(choices=[('none', 'None'), ('doctor', 'Doctor'), ('nurse', 'Nurse')], default='', max_length=50),
        ),
    ]
